Encoding:
  Enabled: False
LineLength:
  Max: 600
Documentation:
  Enabled: False
HashSyntax:
  Enabled: False
Style/SpaceBeforeFirstArg:
  Enabled: false
AsciiComments:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
